server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${urls.auth-service}
          predicates:
            - Path=/api/auth/**